spring:
  # redis配置
  redis:
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间（毫秒）
    timeout: 1000ms
mybatis-plus:
  global-config:
    # 关闭自带的banner
    banner: false
    db-config:
      #主键类型 默认使用雪花ID
      #字段策略
      select-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      logic-delete-field: flag
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
  type-aliases-package: com.ddcat.entity
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  registry:
    type: nacos
  config:
    type: nacos
  service:
    vgroup-mapping:
      my_test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
dubbo:
  scan:
    # Dubbo 服务实现类基础包
    base-packages: tech.yunx.api
  # Dubbo 服务暴露的协议配置
  consumer:
    # 服务启动检查 默认开启 服务启动检查依赖服务如不可用抛出异常
    check: false
  protocol:
    name: dubbo
    port: -1
