spring:
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.164.128
    # Redis服务器连接端口
    port: 6379
seata:
  tx-service-group: my_test_tx_group
  registry:
    nacos:
      application: seata-server
      server-addr: 192.168.164.128:8848
      username: nacos
      password: nacos
  config:
    nacos:
      server-addr: 192.168.164.128:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: 465a28fb-e8f1-48ba-ae78-9dd9d77d166e
file:
  # 访问前缀
  prefix: http://localhost:8080/file/ddcat/
  # 服务器存储路径
  path: /data/ddcat/
dubbo:
  registry:
    #   The Spring Cloud Dubbo's registry extension
    address: nacos://192.168.164.128:8848?namespace=privateDubboId
